# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=300)),
                ('Saved_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
